language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- cd pelican
- pelican content -o output -s pelicanconf.py
- ghp-import output
- git push origin gh-pages
